-- Seed: proveedores reales
insert into proveedores (nombre, email, cedula, direccion, pais, paga_a_si_mismo, beneficiario_default_nombre, beneficiario_default_metodo, beneficiario_default_detalle) values
('Maria Isabel Graciano Gaxiola', 'maria.isabelgg21@gmail.com', '1317971845', 'Jacinto Lopez 1824, Cd Obregon', 'Mexico', false, NULL, NULL, NULL),
('Ericka Marleny Molina Mejia', 'e60334853@gmail.com', '3282088631708', 'Chiquimula', 'Guatemala', false, NULL, NULL, NULL),
('Rigoberto Alexander Chabrol Bryant', 'alexanderchabrol01@gmail.com', '601-280590-0001H', 'Colonia 9 de junio, Nicaragua', 'Nicaragua', false,
  'Hernan Rigoberto Chabrol Duarte', 'Transferencia bancaria', 'Banco Lafise Nicaragua, cuenta 117233958, cedula 601-260366-0003X, tel +505 5803-2217, email alexanderchabrol02@gmail.com'),
('Douglas Martin Cano Bucardo', 'douglascano1986@gmail.com', '241-250286-0004V', 'Bo Carlos Nunez, Nicaragua', 'Nicaragua', true, NULL, NULL, NULL),
('Earny Alejandro Atily Stubb', 'earnybusiness@gmail.com', '601-161280-0000F', 'Bluefields', 'Nicaragua', true, NULL, NULL, NULL);

-- Seed: interpretes (planilla de Julio 2026, 63 personas)
insert into interpretes (nombre, email, pais, proveedor_id, estado, metodo_pago) values
('Alba Lucia Arostegui Rizo', 'albaarostegui8@gmail.com', 'Nicaragua', NULL, 'Activo', 'Payoneer'),
('Ammy Peraza', 'ammiperaza90@gmail.com', 'Salvador', NULL, 'Activo', 'Payoneer'),
('Octavio David Gomez Sosa', 'maria.isabelgg21@gmail.com', 'Mexico', (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Isabella Valentina Reyes Ayala', 'maria.isabelgg21@gmail.com', 'Ecuador', (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Anthoni Centeno', 'anthony.jarquin18@gmail.com', NULL, NULL, 'Activo', 'Payoneer'),
('Juan Andres Bernal Calla', 'maria.isabelgg21@gmail.com', 'Mexico', (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Aylin Galante Rosso', 'ailingalanterosso@gmail.com', NULL, NULL, 'Activo', 'Payoneer'),
('Barbara Shajairah Nicho Ebanks', 'e60334853@gmail.com', NULL, (select id from proveedores where nombre = 'Rigoberto Alexander Chabrol Bryant'), 'Activo', 'Transferencia bancaria'),
('Beverly Mariany Blanco Gonzales', 'e60334853@gmail.com', NULL, (select id from proveedores where nombre = 'Ericka Marleny Molina Mejia'), 'Activo', 'Payoneer'),
('Carmen Abigail Romero Iraeta', 'e60334853@gmail.com', 'Mexico', (select id from proveedores where nombre = 'Ericka Marleny Molina Mejia'), 'Activo', 'Payoneer'),
('Marcelo Trigo Flores', 'maria.isabelgg21@gmail.com', 'Bolivia', (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Sara Astrid Evadista Perez', 'maria.isabelgg21@gmail.com', NULL, (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Daniella Beraun faura', 'daniellafaura.traducciones@gmail.com', 'Peru', NULL, 'Activo', 'Transferencia bancaria'),
('Diego Calquin Campos', 'e60334853@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Ericka Marleny Molina Mejia'), 'Activo', 'Payoneer'),
('douglas Martin cano Bucardo', 'douglascano1986@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Douglas Martin Cano Bucardo'), 'Activo', 'Payoneer'),
('Eddy Anthony Bendliss Castillo', 'edbendliss@gmail.com', 'Nicaragua', NULL, 'Activo', 'Payoneer'),
('emanuel orellana', 'ema90.eo@gmail.com', 'Guatemala', NULL, 'Activo', 'Transferencia bancaria'),
('mario enrique wug andrade', 'maria.isabelgg21@gmail.com', 'Mexico', (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Ethan Garcia', 'earnybusiness@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Earny Alejandro Atily Stubb'), 'Activo', 'Payoneer'),
('Hector Salguero Miranda', 'hxsmoker@gmail.com', 'Salvador', NULL, 'Activo', 'Payoneer'),
('iris Martinez Pitrie', 'earnybusiness@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Earny Alejandro Atily Stubb'), 'Activo', 'Payoneer'),
('Jaik Justice Bryan Downs', 'bryandownz16@gmail.com', 'Nicaragua', NULL, 'Activo', 'Transferencia bancaria'),
('Jefferson Hodgson', 'jeffersonchollette100188@gmail.com', 'Nicaragua', NULL, 'Activo', 'Payoneer'),
('Jessica Hernandez', 'earnybusiness@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Earny Alejandro Atily Stubb'), 'Activo', 'Payoneer'),
('Jeyce Ines Fredericks', 'inesbrooks0606@gmail.com', 'Nicaragua', NULL, 'Activo', 'Payoneer'),
('Arfaxad Requejo', 'maria.isabelgg21@gmail.com', NULL, (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('cassandra de los cobos', 'maria.isabelgg21@gmail.com', 'Mexico', (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Jose Mauricio Rubio Arabelo', 'joserubio2914@gmail.com', 'Salvador', NULL, 'Activo', 'Payoneer'),
('Daniel Josue Montiel Matos', 'maria.isabelgg21@gmail.com', 'Venezuela', (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Juan Gabriel Peralta Rios', 'alexanderchabrol01@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Rigoberto Alexander Chabrol Bryant'), 'Activo', 'Transferencia bancaria'),
('Julio Rodrigo Chanchavac Gutierrez', 'rodrigochanchavacg@gmail.com', NULL, NULL, 'Activo', 'Payoneer'),
('Eric Rollano', 'maria.isabelgg21@gmail.com', NULL, (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Kebyn Steve Guevara Umaña', 'kebynsteveguevaraumana@gmail.com', NULL, NULL, 'Activo', 'Payoneer'),
('Ignacio Angulo Andrade', 'maria.isabelgg21@gmail.com', 'Venezuela', (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Kevin Esli Marroquin Cos', 'e60334853@gmail.com', 'Guatemala', (select id from proveedores where nombre = 'Ericka Marleny Molina Mejia'), 'Activo', 'Payoneer'),
('Leisha Dixon', 'alexanderchabrol01@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Rigoberto Alexander Chabrol Bryant'), 'Activo', 'Transferencia bancaria'),
('Jonatan Ayala chacon', 'maria.isabelgg21@gmail.com', 'El Salvador', (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Lituanya Ivette Saldivar Clair', 'earnybusiness@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Earny Alejandro Atily Stubb'), 'Activo', 'Payoneer'),
('Maria Gabriela Raudales Rush', 'gabrielaraudales@hotmail.com', 'Honduras', NULL, 'Activo', 'Transferencia bancaria'),
('Luis Otero Gomez', 'maria.isabelgg21@gmail.com', NULL, (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Mario Henry Willams', 'maxt2020mari@gmail.com', NULL, NULL, 'Activo', 'Transferencia bancaria'),
('Marlyn Bryant', 'alexanderchabrol01@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Rigoberto Alexander Chabrol Bryant'), 'Activo', 'Transferencia bancaria'),
('Martha Garcia Hernandez', 'marthamgarcia09@gmail.com', 'Nicaragua', NULL, 'Activo', 'Payoneer'),
('Morlan Pineer Lopez', NULL, NULL, NULL, 'Onboarding', 'Payoneer'),
('Nicole Francesca Houghton Lazo', 'nicolefrancescahoughtonlazo@gmail.com', 'Peru', NULL, 'Activo', 'Transferencia bancaria'),
('Nilda Jennifer Amesquita Perez Leon', 'gigi_amesquita@hotmail.com', 'Peru', NULL, 'Activo', 'Transferencia bancaria'),
('OSCAR EDUARDO PRUNONOSA SANTANA', 'oscarprunonosa@yahoo.com', 'Nicaragua', NULL, 'Activo', 'Payoneer'),
('Paulina Gutierrez', 'maria.isabelgg21@gmail.com', 'Mexico', (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Roger Ricardo Huaita', 'oscarprunonosa@yahoo.com', 'Peru', NULL, 'Activo', 'Payoneer'),
('ROBERTO DAVIDSON GURDIAN CENTENO', 'douglascano1986@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Douglas Martin Cano Bucardo'), 'Activo', 'Payoneer'),
('Patricia Naranjo Lopez', 'maria.isabelgg21@gmail.com', 'Mexico', (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Shanell Mishelly Terry Hansack', 'earnybusiness@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Earny Alejandro Atily Stubb'), 'Activo', 'Payoneer'),
('Shannon Cristeen Forbes Jones', 'earnybusiness@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Earny Alejandro Atily Stubb'), 'Activo', 'Payoneer'),
('Silvia Guillen Santos', 'silviayamileth.guillen@gmail.com', 'Nicaragua', NULL, 'Activo', 'Payoneer'),
('Valentina aLVAREZ Burgos', 'maria.isabelgg21@gmail.com', NULL, (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Activo', 'Transferencia bancaria'),
('Walter jose hernandez blandon', 'douglascano1986@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Douglas Martin Cano Bucardo'), 'Activo', 'Payoneer'),
('WINELEE ALISHIMA DOWNS BENT', 'earnybusiness@gmail.com', 'Nicaragua', (select id from proveedores where nombre = 'Earny Alejandro Atily Stubb'), 'Activo', 'Payoneer'),
('Ximena Lizzeth Lopez Martinez', 'e60334853@gmail.com', NULL, (select id from proveedores where nombre = 'Ericka Marleny Molina Mejia'), 'Activo', 'Payoneer'),
('Lila Lucina Ugarte Melgar', NULL, 'Bolivia', NULL, 'Onboarding', 'Payoneer'),
('Jacob Condori', NULL, 'Bolivia', NULL, 'Onboarding', 'Payoneer'),
('Carlos Vinck Ascencio', NULL, 'Mexico', NULL, 'Onboarding', 'Transferencia bancaria'),
('Fernanda Andrade Me', NULL, 'Mexico', NULL, 'Onboarding', 'Payoneer'),
('Maria del Carmen Peredo Flores', NULL, NULL, (select id from proveedores where nombre = 'Maria Isabel Graciano Gaxiola'), 'Onboarding', 'Transferencia bancaria');

-- Seed: minutos de Julio 2026
insert into minutos_periodo (interprete_id, periodo, plataforma, minutos, tarifa) values
((select id from interpretes where nombre = 'Alba Lucia Arostegui Rizo'), '2026-07-01', 'LB', 6006, 0.1),
((select id from interpretes where nombre = 'Alba Lucia Arostegui Rizo'), '2026-07-01', 'TTG', 6, 0.1),
((select id from interpretes where nombre = 'Alba Lucia Arostegui Rizo'), '2026-07-01', 'Propio', 5742, 0.1),
((select id from interpretes where nombre = 'Ammy Peraza'), '2026-07-01', 'Propio', 2103, 0.1),
((select id from interpretes where nombre = 'Octavio David Gomez Sosa'), '2026-07-01', 'Propio', 5753, 0.1),
((select id from interpretes where nombre = 'Isabella Valentina Reyes Ayala'), '2026-07-01', 'Propio', 5371, 0.12),
((select id from interpretes where nombre = 'Anthoni Centeno'), '2026-07-01', 'Propio', 2203, 0.1),
((select id from interpretes where nombre = 'Juan Andres Bernal Calla'), '2026-07-01', 'Propio', 4401, 0.12),
((select id from interpretes where nombre = 'Aylin Galante Rosso'), '2026-07-01', 'LB', 44, 0.1),
((select id from interpretes where nombre = 'Aylin Galante Rosso'), '2026-07-01', 'Propio', 123, 0.1),
((select id from interpretes where nombre = 'Barbara Shajairah Nicho Ebanks'), '2026-07-01', 'TTG', 1282, 0.1),
((select id from interpretes where nombre = 'Beverly Mariany Blanco Gonzales'), '2026-07-01', 'Propio', 6622, 0.11),
((select id from interpretes where nombre = 'Carmen Abigail Romero Iraeta'), '2026-07-01', 'Propio', 1848, 0.1),
((select id from interpretes where nombre = 'Marcelo Trigo Flores'), '2026-07-01', 'Propio', 3530, 0.12),
((select id from interpretes where nombre = 'Sara Astrid Evadista Perez'), '2026-07-01', 'Propio', 3318, 0.1),
((select id from interpretes where nombre = 'Daniella Beraun faura'), '2026-07-01', 'Propio', 343, 0.1),
((select id from interpretes where nombre = 'Diego Calquin Campos'), '2026-07-01', 'Propio', 4693, 0.1),
((select id from interpretes where nombre = 'douglas Martin cano Bucardo'), '2026-07-01', 'LB', 974, 0.1),
((select id from interpretes where nombre = 'Eddy Anthony Bendliss Castillo'), '2026-07-01', 'TTG', 270, 0.1),
((select id from interpretes where nombre = 'Eddy Anthony Bendliss Castillo'), '2026-07-01', 'Propio', 4046, 0.1),
((select id from interpretes where nombre = 'emanuel orellana'), '2026-07-01', 'TTG', 266, 0.1),
((select id from interpretes where nombre = 'emanuel orellana'), '2026-07-01', 'Propio', 1677, 0.1),
((select id from interpretes where nombre = 'mario enrique wug andrade'), '2026-07-01', 'Propio', 113, 0.1),
((select id from interpretes where nombre = 'Ethan Garcia'), '2026-07-01', 'Propio', 7603, 0.1),
((select id from interpretes where nombre = 'Hector Salguero Miranda'), '2026-07-01', 'Propio', 1679, 0.1),
((select id from interpretes where nombre = 'iris Martinez Pitrie'), '2026-07-01', 'Propio', 600, 0.1),
((select id from interpretes where nombre = 'Jaik Justice Bryan Downs'), '2026-07-01', 'Propio', 1459, 0.1),
((select id from interpretes where nombre = 'Jefferson Hodgson'), '2026-07-01', 'TTG', 679, 0.1),
((select id from interpretes where nombre = 'Jefferson Hodgson'), '2026-07-01', 'Propio', 5774, 0.1),
((select id from interpretes where nombre = 'Jessica Hernandez'), '2026-07-01', 'Propio', 1712, 0.1),
((select id from interpretes where nombre = 'Jeyce Ines Fredericks'), '2026-07-01', 'Propio', 2973, 0.1),
((select id from interpretes where nombre = 'Arfaxad Requejo'), '2026-07-01', 'LB', 5423, 0.1),
((select id from interpretes where nombre = 'cassandra de los cobos'), '2026-07-01', 'LB', 4139, 0.1),
((select id from interpretes where nombre = 'Jose Mauricio Rubio Arabelo'), '2026-07-01', 'MAVEN', 26, 0.1),
((select id from interpretes where nombre = 'Jose Mauricio Rubio Arabelo'), '2026-07-01', 'TTG', 124, 0.1),
((select id from interpretes where nombre = 'Jose Mauricio Rubio Arabelo'), '2026-07-01', 'Propio', 1446, 0.1),
((select id from interpretes where nombre = 'Daniel Josue Montiel Matos'), '2026-07-01', 'LB', 6807, 0.1),
((select id from interpretes where nombre = 'Juan Gabriel Peralta Rios'), '2026-07-01', 'Propio', 4552, 0.1),
((select id from interpretes where nombre = 'Julio Rodrigo Chanchavac Gutierrez'), '2026-07-01', 'Propio', 1822, 0.1),
((select id from interpretes where nombre = 'Eric Rollano'), '2026-07-01', 'LB', 3501, 0.1),
((select id from interpretes where nombre = 'Kebyn Steve Guevara Umaña'), '2026-07-01', 'Propio', 4885, 0.1),
((select id from interpretes where nombre = 'Ignacio Angulo Andrade'), '2026-07-01', 'TTG', 498, 0.1),
((select id from interpretes where nombre = 'Kevin Esli Marroquin Cos'), '2026-07-01', 'Propio', 6256, 0.11),
((select id from interpretes where nombre = 'Leisha Dixon'), '2026-07-01', 'Propio', 2101, 0.1),
((select id from interpretes where nombre = 'Jonatan Ayala chacon'), '2026-07-01', 'LB', 503, 0.1),
((select id from interpretes where nombre = 'Lituanya Ivette Saldivar Clair'), '2026-07-01', 'Propio', 2830, 0.1),
((select id from interpretes where nombre = 'Maria Gabriela Raudales Rush'), '2026-07-01', 'TTG', 276, 0.1),
((select id from interpretes where nombre = 'Maria Gabriela Raudales Rush'), '2026-07-01', 'Propio', 5307, 0.1),
((select id from interpretes where nombre = 'Luis Otero Gomez'), '2026-07-01', 'LB', 5198, 0.1),
((select id from interpretes where nombre = 'Mario Henry Willams'), '2026-07-01', 'TTG', 3, 0.1),
((select id from interpretes where nombre = 'Mario Henry Willams'), '2026-07-01', 'Propio', 2570, 0.1),
((select id from interpretes where nombre = 'Marlyn Bryant'), '2026-07-01', 'Propio', 3345, 0.1),
((select id from interpretes where nombre = 'Martha Garcia Hernandez'), '2026-07-01', 'Propio', 3865, 0.1),
((select id from interpretes where nombre = 'Morlan Pineer Lopez'), '2026-07-01', 'TTG', 220, 0.1),
((select id from interpretes where nombre = 'Morlan Pineer Lopez'), '2026-07-01', 'Propio', 4439, 0.1),
((select id from interpretes where nombre = 'Nicole Francesca Houghton Lazo'), '2026-07-01', 'Propio', 1394, 0.1),
((select id from interpretes where nombre = 'Nilda Jennifer Amesquita Perez Leon'), '2026-07-01', 'LB', 532, 0.1),
((select id from interpretes where nombre = 'Nilda Jennifer Amesquita Perez Leon'), '2026-07-01', 'Propio', 514, 0.1),
((select id from interpretes where nombre = 'Paulina Gutierrez'), '2026-07-01', 'TTG', 681, 0.1),
((select id from interpretes where nombre = 'Roger Ricardo Huaita'), '2026-07-01', 'TTG', 43, 0.1),
((select id from interpretes where nombre = 'Roger Ricardo Huaita'), '2026-07-01', 'Propio', 2834, 0.1),
((select id from interpretes where nombre = 'ROBERTO DAVIDSON GURDIAN CENTENO'), '2026-07-01', 'TTG', 295, 0.1),
((select id from interpretes where nombre = 'ROBERTO DAVIDSON GURDIAN CENTENO'), '2026-07-01', 'Propio', 2570, 0.1),
((select id from interpretes where nombre = 'Patricia Naranjo Lopez'), '2026-07-01', 'LB', 363, 0.1),
((select id from interpretes where nombre = 'Shanell Mishelly Terry Hansack'), '2026-07-01', 'Propio', 3227, 0.1),
((select id from interpretes where nombre = 'Shannon Cristeen Forbes Jones'), '2026-07-01', 'Propio', 4273, 0.1),
((select id from interpretes where nombre = 'Silvia Guillen Santos'), '2026-07-01', 'TTG', 75, 0.1),
((select id from interpretes where nombre = 'Silvia Guillen Santos'), '2026-07-01', 'Propio', 622, 0.1),
((select id from interpretes where nombre = 'Valentina aLVAREZ Burgos'), '2026-07-01', 'TTG', 326, 0.1),
((select id from interpretes where nombre = 'Walter jose hernandez blandon'), '2026-07-01', 'Propio', 1700, 0.1),
((select id from interpretes where nombre = 'WINELEE ALISHIMA DOWNS BENT'), '2026-07-01', 'Propio', 338, 0.1),
((select id from interpretes where nombre = 'Ximena Lizzeth Lopez Martinez'), '2026-07-01', 'Propio', 9350, 0.11),
((select id from interpretes where nombre = 'Lila Lucina Ugarte Melgar'), '2026-07-01', 'Propio', 3609, 0.1),
((select id from interpretes where nombre = 'Jacob Condori'), '2026-07-01', 'Propio', 989, 0.1),
((select id from interpretes where nombre = 'Carlos Vinck Ascencio'), '2026-07-01', 'Propio', 1293, 0.1),
((select id from interpretes where nombre = 'Fernanda Andrade Me'), '2026-07-01', 'Propio', 2999, 0.1),
((select id from interpretes where nombre = 'Maria del Carmen Peredo Flores'), '2026-07-01', 'LB', 4, 0.1);